#-------------------------------
# General Site Settings
title: Portfolio
logo: memoticon.png # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Im Hyejeong
  image: 01.jpg
  say-hello: 안녕하세요, <strong>임혜정</strong>입니다.
  bio: 데이터 분석 직무 전환을 준비하고 있는 임혜정입니다. <br> 새로운 지식을 빠르게 습득하고, 배운 내용을 업무에 적용하는 것을 즐깁니다. iOS 개발자로 3년간 서비스를 개발, 유지해온 경험을 바탕으로 조직 내에서 빠르게 성장할 자신이 있습니다.


#-------------------------------
# Contact links
#twitter: https://twitter.com/ # Add your Twitter handle
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
email: imhj973@gmail.com


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
